### ISSUE TITLE
Possible to add Portable VLC player?

### ISSUE THREAD

**Issue by SysAdminDoc** [SiL3NC3/PortableRegistrator#1]
This is a handy tool but is there a way to fix video file associations with portable VLC?

**Comment by SiL3NC3** [comment]
I was also thinking about being flexible for other app needs. That is what the config file is for.
Consider adding a new section for video players like so:
```
 <AppType>
      <Name>Videoplayer-Program</Name>
      <OpenParameters>"%1"</OpenParameters>
      <FileAssociations>
        <string>.mp4</string>
        <string>.mkv</string>
        <string>.avi</string>
        <string>...</string>
      </FileAssociations>
      <URLAssociations>
        <string>vlc??</string>
      </URLAssociations>
 </AppType>
```   
Add an entry for all supported file associations of VLC. They can be figured out with a little bit of research.
It should also possible to use an URL association with PortableRegistrator to open VLC via web links, but this is just a guess and untested! If this is not needed just remove the line with 'vlc??'.

Good luck.
