### ISSUE TITLE
How to use PortableRegistrator on a PC where u can only install portable apps because you are not admin of your PC?

### ISSUE THREAD

**Issue by Tristan107** [SiL3NC3/PortableRegistrator#10]
It looks like PortableRegistrator requires to be windows admin which defeats the purpose of registering portable apps on a PC where u are not admin : 
![image](https://user-images.githubusercontent.com/12673099/212318193-749df164-739f-4812-9d73-8765c0325957.png)

**Comment by SiL3NC3** [comment]
Not possible.
Writing registry keys requires elevated rights.
