### ISSUE TITLE
Renewed Script 

### ISSUE THREAD

**Issue by DMmoinmoin** [SiL3NC3/PortableRegistrator#11]
Hi SiL3NC3,
Holgi is not registered on GitHub. Therefore I post the link once.
He has renewed the script. You can take a look at it. https://www.deskmodder.de/phpBB3/viewtopic.php?t=27857#p405116
/moinmoin

**Comment by SiL3NC3** [comment]
Cheers DM,

all these apps are already implemented in the code.
When you delete your existing config file and restart Portable Registrator, it will generate a new config file with all newly implemented apps.

![image](https://user-images.githubusercontent.com/694970/220433323-8d6a04aa-2234-40e7-b7e9-968554e8a100.png)

Holgi is fully supported. ;)
NJoy.

//SiL

**Comment by SiL3NC3** [comment]
Re-checked it and release a "small fix" update.

NJoy.
