### ISSUE TITLE
How does PortableRegistrator work?

### ISSUE THREAD

**Issue by paradoxicallist** [SiL3NC3/PortableRegistrator#12]
I got some doubts about how it really works and I uploaded a video to show what I really mean.

https://streamable.com/o5e945

**Comment by SiL3NC3** [comment]
Portable Registrator is only adding the file-association for the type in the registry, as an available file-type (so to say).
Assigning/using it, is one step to do manually...

So the tool is just doing the "magic" of that you CAN assign it and have it in the available Apps. ;)

... but it is only one time.
