### ISSUE TITLE
Cannot launch 1.2 & 1.3

### ISSUE THREAD

**Issue by freddie-o** [SiL3NC3/PortableRegistrator#13]
What am I missing? v1.2 & v1.3 will not launch. v1.1 works fine.

**Comment by SiL3NC3** [comment]
Any log output?

**Comment by freddie-o** [comment]
None. Nothing happens.

**Comment by Cheshire-Behemoth** [comment]
The same problem

**Comment by patrickdrd** [comment]
same here, windows 8.1

**Comment by SiL3NC3** [comment]
A good point for issue #13 ;)))

I will add logging support, that we can figure out the problem.
Cannot get a glue what'r happening, because I did not change any critical stuff during the last version, imho.

Sorry for the inconvenience, folkz.

**Comment by SiL3NC3** [comment]
Grab the new release and post log files, dudes. ;)

**Comment by Cheshire-Behemoth** [comment]
With the release of the new version 1.4, the problem did not go away. The program does not start and outwardly it does not manifest itself in any way. No log file appears next to it. How to get this log file and show you?

**Comment by pstein** [comment]
same here with v1.4 on Win 10 21H2

**Comment by SiL3NC3** [comment]
Attach them here...

Just copy the path to the file and paste it in the text... Or just copy the contents of the logfile as text.

I was aware, that the problem is still existing, I need to know, WHAT is causing the problem.
... I lost my crystal ball. ;)

So just paste log information and I CAN have a look at...

THX, dudes.

**Comment by SiL3NC3** [comment]
If no log was written, then maybe it is a PC based problem?!
Try disabling Defender and other possibly blocking apps...

**Comment by Cheshire-Behemoth** [comment]
Defender is disabled. The configuration file is not created. Apparently, the process does not even reach its creation.

**Comment by SiL3NC3** [comment]
@Cheshire-Behemoth: Thank you for your instant reply.

Antivirus is not blocking the file in any way?
I don't get a glue, guys. On my machine it is working fine...

Please understand, I cannot fix, what I cannot reproduce... :((

Check the Windows Eventviewer, maybe some useful there.
If there is an error, it should be (at least) tracked there...

**Comment by Cheshire-Behemoth** [comment]
UAC is disabled. The program starts from a disk that is completely excluded from the antivirus. Just in case, I also turned off the antivirus monitor that checks the memory in real time. I have NOD32 internet security. When I run eventvwr.msc, I do not find any marks about the operation of the program at all, neither in the program section, nor in the security section, nor in the installation, not in the system.

**Comment by Cheshire-Behemoth** [comment]
Everything is fine with Windows, the latest updates are in place, Microsoft Visual C ++ 2005--2022 is fully installed, the system passes the SFC test and system storage integrity tests

**Comment by SiL3NC3** [comment]
OK... was just an idea... nothing personal. ;)
This is so weird...

**Comment by Cheshire-Behemoth** [comment]
I myself see this for the first time. It is usually seen that the program starts, but then closes, and then nothing happens at all. I checked its launch on a laptop with an old version of Win10 and another computer. The situation is the same everywhere.

**Comment by Cheshire-Behemoth** [comment]
Try to check the code of the program through the GPT chat. I heard a lot of reviews that he helps, maybe a friend will help you.

**Comment by Tback1** [comment]
@SiL3NC3  I also have this quesion on Windows 10 LTSC 2021

I disabled the defender、UAC、and other would blocked the app run
but it run nothing on the Windows

so I Tried to on CLI
so it could run and just output the default PortableRegistrator.conf with the same path

![image](https://user-images.githubusercontent.com/8872546/229631854-dbc99588-e034-4930-b897-3fe1daf527df.png)

**Comment by SiL3NC3** [comment]
@Tback1 

Have you tried to delete the conf file? It is also not being generated freshly?

**Comment by SiL3NC3** [comment]
I removed the CLI stuff from the gui and added CLI as a separated project (exe).
Please report back, if this helps, that the GUI is opening again.
Thank you for your patience.

**Comment by Cheshire-Behemoth** [comment]
The version of Portableregistrator.exe from the archive Portableregistrator_v1.5.zip launched normally, the file Portableregistrator.conf was created nearby. PortableregistratorCli.exe is launched in the form of a flickering black window, as when starting a command file in Windows and immediately the window is spent. Nothing else happens.

**Comment by freddie-o** [comment]
Yep v1.5 now works. Thank you @SiL3NC3 So it was CLI

**Comment by pstein** [comment]
Works now here too
