### ISSUE TITLE
Can you add a silent mode?

### ISSUE THREAD

**Issue by imkira3** [SiL3NC3/PortableRegistrator#14]
I was just gonna use this for a single app, it would be nice if I could skip using the GUI and automatically assign all registered extensions for a given AppType, you could define a "Silent Mode" in the configuration file perhaps? I just want something I can double click on and have it do all the work, like the app I made to configure video player settings. Originally I was gonna do this with a batch file like this: `assoc .mkv=PotPlayerPortable.MKV&&ftype PotPlayerPortable.MKV="PotPlayerPortable.exe" "%1"` but assoc and ftype don't support relative paths.

**Comment by SiL3NC3** [comment]
I will think about it in a next release.

**Comment by imkira3** [comment]
Thanks :) I could include it in portable releases then, providing a simple way to configure the launcher. Lots of portable apps from PortableApps.com have the issue of referring to the base app rather than the portable launcher, only way to configure extensions properly is during installation so a substitute program is necessary to configure them, so I at least would find that quite useful, a simple app in the same folder as the launcher ready to help a portable folder take root without a full re-install
