### ISSUE TITLE
SumatraPDF PDF File Type Not In List

### ISSUE THREAD

**Issue by SW-GitHub-2017** [SiL3NC3/PortableRegistrator#16]
The SumatraPDF file types don't list PDF in the files list.

**Comment by SiL3NC3** [comment]
It should be, thanks for the info.
Will be fixed in the next release.

**Comment by SiL3NC3** [comment]
v1.4 - grab the new release. ;)

**Comment by SW-GitHub-2017** [comment]
I don't know if this matters or not as far as the way your app registers programs but in the list in the config, pdf is shown as "<string>pdf</string>" without the period before pdf.  If it has no effect on registering this type, which was already registered on my system prior, then thanks for updating it.  I saw this as being a possible problem for other users who might try to register that type with your app.

By the way, your app is awesome and I appreciate you hard work!
