### ISSUE TITLE
Possible Missing Font

### ISSUE THREAD

**Issue by SW-GitHub-2017** [SiL3NC3/PortableRegistrator#17]
I have circled 2 items on the app that have what may be a font issue.  I believe I don't the font that is being used for the "Delete" button and the Made with "Heart" symbol at the bottom.
![PortableRegistrar](https://user-images.githubusercontent.com/26510119/226789867-ff47d528-8884-41cf-bfba-72003b8add30.jpg)

**Comment by SiL3NC3** [comment]
SegoeUI is assigned to this button.
The system needs to have it.

https://github.com/mrbvrz/segoe-ui-linux/tree/master/font

**Comment by SW-GitHub-2017** [comment]
I have those fonts on my system already, but overwrite them with the ones from the archive in case there were updated.  It still shows the same as the photo.  Not sure why.
![SegoeUI](https://user-images.githubusercontent.com/26510119/229383517-07a96221-3eb3-4885-86ca-0586086f32be.png)

**Comment by SW-GitHub-2017** [comment]
I also downloaded version 1.4 just so you know.

**Comment by SiL3NC3** [comment]
Strange things are happening...
Maybe I will switch to a PNG instead of using Unicode to prevent this gui issue... :|

**Comment by SiL3NC3** [comment]
In 1.5 I forgot to change the heart symbol... ;)
X is now a standard X as it is. Should display well now on all machines.

**Comment by SiL3NC3** [comment]
-closed-
