### ISSUE TITLE
IrfanView Image File Formats

### ISSUE THREAD

**Issue by SW-GitHub-2017** [SiL3NC3/PortableRegistrator#18]
GitHub wouldn't let me attach the text file.

In case you'd like to add this:

    <AppType>
      <Name>IrfanView Image-Viewer</Name>
      <OpenParameters>"%1"</OpenParameters>
      <FileAssociations>
        <string>.3fr</string>
        <string>.acr</string>
        <string>.ani</string>
        <string>.arw</string>
        <string>.b3d</string>
        <string>.bmp</string>
        <string>.cam</string>
        <string>.cdr</string>
        <string>.cgm</string>
        <string>.cin</string>
        <string>.clp</string>
        <string>.cmx</string>
        <string>.cr2</string>
        <string>.cr3</string>
        <string>.crw</string>
        <string>.cur</string>
        <string>.dcm</string>
        <string>.dcr</string>
        <string>.dcx</string>
        <string>.dds</string>
        <string>.dib</string>
        <string>.djvu</string>
        <string>.dng</string>
        <string>.dpx</string>
        <string>.dwg</string>
        <string>.dxf</string>
        <string>.ecw</string>
        <string>.emf</string>
        <string>.erf</string>
        <string>.exr</string>
        <string>.fits</string>
        <string>.flc</string>
        <string>.fli</string>
        <string>.flif</string>
        <string>.fpx</string>
        <string>.g3</string>
        <string>.gif</string>
        <string>.hdp</string>
        <string>.heic</string>
        <string>.hpgl</string>
        <string>.icl</string>
        <string>.ico</string>
        <string>.ics</string>
        <string>.ids</string>
        <string>.iff</string>
        <string>.img</string>
        <string>.iw44</string>
        <string>.j2k</string>
        <string>.jfif</string>
        <string>.jls</string>
        <string>.jng</string>
        <string>.jp2</string>
        <string>.jpc</string>
        <string>.jpe</string>
        <string>.jpeg</string>
        <string>.jpf</string>
        <string>.jpg</string>
        <string>.jpm</string>
        <string>.jxl</string>
        <string>.jxr</string>
        <string>.lbm</string>
        <string>.mng</string>
        <string>.mos</string>
        <string>.mpo</string>
        <string>.mrsid</string>
        <string>.mrw</string>
        <string>.nef</string>
        <string>.nrw</string>
        <string>.orf</string>
        <string>.pbm</string>
        <string>.pcd</string>
        <string>.pcx</string>
        <string>.pdn</string>
        <string>.pef</string>
        <string>.pgm</string>
        <string>.plt</string>
        <string>.png</string>
        <string>.ppm</string>
        <string>.psb</string>
        <string>.psd</string>
        <string>.psp</string>
        <string>.pspimage</string>
        <string>.qoi</string>
        <string>.raf</string>
        <string>.ras</string>
        <string>.raw</string>
        <string>.rgb</string>
        <string>.rle</string>
        <string>.rw2</string>
        <string>.rwl</string>
        <string>.sid</string>
        <string>.sff</string>
        <string>.sfw</string>
        <string>.sgi</string>
        <string>.srf</string>
        <string>.srw</string>
        <string>.sun</string>
        <string>.svg</string>
        <string>.tga</string>
        <string>.tif</string>
        <string>.tiff</string>
        <string>.wad</string>
        <string>.wbc</string>
        <string>.wbmp</string>
        <string>.wbz</string>
        <string>.wdp</string>
        <string>.webp</string>
        <string>.wmf</string>
        <string>.wsq</string>
        <string>.x3f</string>
        <string>.xbm</string>
        <string>.xcf</string>
        <string>.xpm</string>
      </FileAssociations>
      <URLAssociations>
        <string>view</string>
      </URLAssociations>
    </AppType>

**Comment by SiL3NC3** [comment]
You need to do a fork and then commit to your own repo.
With a pull-request your changes will then be able to be imported in the main repo.

**Comment by SiL3NC3** [comment]
-closed-
