### ISSUE TITLE
unsupport windows 11

### ISSUE THREAD

**Issue by hangangcn** [SiL3NC3/PortableRegistrator#19]
good job!,but on windows11,it is unusful

**Comment by SiL3NC3** [comment]
sorry, right now I don't have time to prepare a W11 machine.

**Comment by ajariel** [comment]
just used the tool to set up mullvad browser as the default browser on my win11 machine, worked flawlessly. 
Windows 11 Pro 10.0.22621 Build 22621

**Comment by ZhalekXishailri** [comment]
I was also able to use it to setup Mullvad Browser as the default browser on my Win11 machine without any issues.
Windows 11 Home 22H2

**Comment by SiL3NC3** [comment]
> good job!,but on windows11,it is unusful

Did you see the elevation request on startup?
Did it run with Admin rights?

From the replies I can see, that W11 is working.
Hope you got it working so far...

If not, please open another issue.
Thx.

-closed-
