### ISSUE TITLE
My PortableRegistrator.conf

### ISSUE THREAD

**Issue by koriaba** [SiL3NC3/PortableRegistrator#2]
<?xml version="1.0"?>
<Configuration xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <AppTypes>
    <AppType>
      <Name>Web-Browser</Name>
      <OpenParameters>-url "%1"</OpenParameters>
      <FileAssociations>
        <string>.htm</string>
        <string>.html</string>
        <string>.shtml</string>
        <string>.xht</string>
        <string>.xhtml</string>
      </FileAssociations>
      <URLAssociations>
        <string>http</string>
        <string>https</string>
        <string>ftp</string>
      </URLAssociations>
    </AppType>
    <AppType>
      <Name>Mail-Program</Name>
      <OpenParameters>"%1"</OpenParameters>
      <FileAssociations>
        <string>.xpi</string>
        <string>.eml</string>
        <string>.msg</string>
        <string>.ics</string>
        <string>.mbox</string>
      </FileAssociations>
      <URLAssociations>
        <string>mailto</string>
      </URLAssociations>
    </AppType>
	<AppType>
      <Name>KMPlayerPortable</Name>
      <OpenParameters>"%1"</OpenParameters>
      <FileAssociations>
        <string>.avi</string>
        <string>.mkv</string>
        <string>.mp4</string>
        <string>.mov</string>
      </FileAssociations>
		<URLAssociations>
		<string> m3u8</string>
		<string> mp4</string>
		<string> mov</string>
</URLAssociations>
    </AppType>
	<AppType>
      <Name>TelegramPortable_x64</Name>
      <OpenParameters>"%1"</OpenParameters>
      <FileAssociations>
        <string>.xpi</string>
      </FileAssociations>
      <URLAssociations>
        <string></string>
      </URLAssociations>
    </AppType>
	<AppType>
      <Name>FSViewer</Name>
      <OpenParameters>-parameter "%1"</OpenParameters>
      <FileAssociations>
        <string>.jpg</string>
        <string>.gif</string>
		<string>.bmp </string>
		<string>.png</string>
		<string>.ico</string>
      </FileAssociations>
      <URLAssociations>
        <string>view</string>
      </URLAssociations>
    </AppType>
	<AppType>
		<Name>WINRAR</Name>
<OpenParameters> "%1″</OpenParameters>
<FileAssociations>
<string>.7zip</string>
<string>.zip</string>
<string>.rar</string>
<string>.gz</string>
<string>.cab</string>
</FileAssociations>
<URLAssociations>
<string>view</string>
</URLAssociations>
</AppType>
  </AppTypes>
</Configuration>

**Comment by koriaba** [comment]
[PortableRegistrator.log](https://github.com/SiL3NC3/PortableRegistrator/files/8418113/PortableRegistrator.log)

**Comment by SiL3NC3** [comment]
Thank you.
