### ISSUE TITLE
CLI - how do you use it?

### ISSUE THREAD

**Issue by wincmd64** [SiL3NC3/PortableRegistrator#22]
for example, I add my program via GUI - so can you give me example how to use cli with it ?

**Comment by SiL3NC3** [comment]
Sorry, for the late answer.
The CLI is just a small addition for the deskmodder guys.
It can only access the configuration and prints out information from it.
It is not designed to can register or unregister portable apps.

When you run: PortableRegistratorCLI.exe **/?**

You will see the options:
![image](https://github.com/SiL3NC3/PortableRegistrator/assets/694970/ca20b1c2-1e97-4ccd-a6e8-0bf8482eb6ab)

That's (right now) all you can do with it.

Sidenote:
If you want to register an executable to run it anywhere from a cmd prompt, you need to add this to the %PATH% variable of your Windows.
https://techpp.com/2021/08/26/set-path-variable-in-windows-guide/

**Comment by SiL3NC3** [comment]
**Note:**
You cannot register a portable app via the CLI, just use the GUI for registration

-closed-

**Comment by SiL3NC3** [comment]
**Note:**
You cannot register a portable app via the CLI, just use the GUI for registration

-closed-
