### ISSUE TITLE
how to use for mpv and smplayer?

### ISSUE THREAD

**Issue by candrapersada** [SiL3NC3/PortableRegistrator#24]

**Comment by SiL3NC3** [comment]
You could use something like this:

```
    <AppType>
      <Name>SM-Player</Name>
      <OpenParameters>"%1"</OpenParameters>
      <FileAssociations>
        <string>.m3u8</string>
        <string>.mp4</string>
        <string>.mpv</string>
      </FileAssociations>
      <URLAssociations />
    </AppType>
```

After starting PortableRegistrator, it created the file "PortableRegistrator.conf".
Open it with a text editor (Notepad) and add the above lines within the <AppTypes>...</AppTypes> section.

Then after a restart of PortableRegistrator, you should be able to use it properly.

**Comment by SiL3NC3** [comment]
-closed-
