### ISSUE TITLE
Detected as malware

### ISSUE THREAD

**Issue by lwcorp** [SiL3NC3/PortableRegistrator#27]
3 out of 64 [in VirusTotal](https://www.virustotal.com/gui/file/21b3f639d9fab24ed8ec3cf5d85433baffb0f7c499cec675fa41bfe946084eb9) may not be a lot, but it's still bigger than 1...would you considering checking why it happens, and if it's unavoidable report false positives to those specific vendors?
![image](https://github.com/SiL3NC3/PortableRegistrator/assets/1773306/ebe21ce1-8950-4603-9387-8afa66fe8198)

So to be on the safe side, I've tried running it through [Sandboxie](https://github.com/sandboxie-plus/Sandboxie)...and it crashed it. Very few and quite complex programs do that:
![image](https://github.com/SiL3NC3/PortableRegistrator/assets/1773306/1a898152-73d6-411e-b8ce-c01853b03b23)

**Comment by SiL3NC3** [comment]
Yes, it is probably not "wanted", to register an app to use it portable...
I can proove, there is no malware inside.
As source code is provided, you could check this for yourself.

The software is provided as it is, for use at your own risk.

If you cannot trust it, please don't use it.
You could manually edit the registry, as the program is not doing anything else.
Quite simple step.

PortableRegistrator is only offering a handy tool for this.

**For getting rid of the false positive**, just add it to the exclusion in you AV software.

**Comment by lwcorp** [comment]
What is the downside of you as the author submitting a false positive report?
As for Sandboxie, the whole idea is that it makes programs think they are installed for real, small programs are supposed to get tricked without blinking.
