### ISSUE TITLE
thanks for the support NT 5.1

### ISSUE THREAD

**Issue by andika207** [SiL3NC3/PortableRegistrator#3]
apparently it runs perfect on Windows XP.

<a href='https://postimg.cc/6225QjhG' target='_blank'><img src='https://i.postimg.cc/6225QjhG/Snap-Crab-No-Name-2022-4-9-1-37-16-No-00.png' border='0' alt='Snap-Crab-No-Name-2022-4-9-1-37-16-No-00'/></a>

**Comment by SiL3NC3** [comment]
Thank you for sharing.
