### ISSUE TITLE
Beautify file type description in Windows

### ISSUE THREAD

**Issue by sickypedia** [SiL3NC3/PortableRegistrator#5]
After registering an app, I see the description as Appname + TYPE

Can this be improved to show Appname + File, so it looks more natural in windows. Or a config property for user to give description with each extension would be helpful.

![image](https://user-images.githubusercontent.com/73606172/179424275-7eb648fe-a947-4449-af50-2b5af361fafd.png)

**Comment by sickypedia** [comment]
I'm essentially asking for TYPE to be made a variable, instead of it being hard-coded in this line from RegistryHelper.cs
```
Line  68: Registry.SetValue($"HKEY_CLASSES_ROOT\\{prgTYPE}", "", $"{prgNAME} TYPE", RegistryValueKind.String);
```

**Comment by SiL3NC3** [comment]
I will have a look at this, for the next release.

**Comment by SiL3NC3** [comment]
@sickypedia 
What about just removing "TYPE" from the text.
What kind of variable do you think of?

**Comment by SiL3NC3** [comment]
Check v1.1
