### ISSUE TITLE
How to register an custom APP to TEL protocal

### ISSUE THREAD

**Issue by hdu7** [SiL3NC3/PortableRegistrator#7]
![image](https://user-images.githubusercontent.com/67653788/193115386-88a8eeae-f700-4e25-8555-846f93c8bebc.png)
Do you know how to register a custom APP to TEL protocol

**Comment by SiL3NC3** [comment]
You could probably go with a config section like this:

```
    <AppType>
      <Name>My Phoner App</Name>
	  <OpenParameters>"%1"</OpenParameters>
      <FileAssociations>
        <string>.phone</string>
      </FileAssociations>
      <URLAssociations>
        <string>TEL</string>
      </URLAssociations>
    </AppType>
```

If you don't need any FileAssociations, you could delete those lines and try it without first.

URL Association is registering the "protocol" >> "TEL" call.
Similar to "mailto:...." with a mail program.
