### ISSUE TITLE
VLC Portable

### ISSUE THREAD

**Issue by psorincatalin** [SiL3NC3/PortableRegistrator#8]
Would be best that in the next release of the program, the word "Portable" would be dropped from the name. I mean if someone choses to name their program Portable should be their choice, should not be enforced. I understand why "Portable" was added to the name, as some people might also have the regular program installed. But yet again, if people already use this tool they should have a basic understanding of what they are doing. For me, personally, I only have portable programs and when using this tool I see all the time XXXX Portable and XXXX Portable File Type and I need to edit the registry myself, which is becoming a bit of a nuisance.

![image](https://user-images.githubusercontent.com/59143259/195070667-6acb8aba-8f40-4966-92c6-f495d876e44f.png)

![image](https://user-images.githubusercontent.com/59143259/195070477-da5a0903-742e-4a58-9617-7e36e90ba339.png)

Adding my own config for VLC:
[VLC.txt](https://github.com/SiL3NC3/PortableRegistrator/files/9754438/VLC.txt)

`<?xml version="1.0"?>
<Configuration xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <AppTypes>
    <AppType>
      <Name>VLC</Name>
      <OpenParameters>"%1"</OpenParameters>
      <FileAssociations>
		<string>.3ga</string>
		<string>.669</string>
		<string>.a52</string>
		<string>.aac</string>
		<string>.ac3</string>
		<string>.adt</string>
		<string>.adts</string>
		<string>.aif</string>
		<string>.aifc</string>
		<string>.aiff</string>
		<string>.au</string>
		<string>.amr</string>
		<string>.aob</string>
		<string>.ape</string>
		<string>.caf</string>
		<string>.cda</string>
		<string>.dts</string>
		<string>.flac</string>
		<string>.it</string>
		<string>.m4a</string>
		<string>.m4p</string>
		<string>.mid</string>
		<string>.mka</string>
		<string>.mlp</string>
		<string>.mod</string>
		<string>.mp1</string>
		<string>.mp2</string>
		<string>.mp3</string>
		<string>.mpc</string>
		<string>.mpga</string>
		<string>.oga</string>
		<string>.oma</string>
		<string>.opus</string>
		<string>.qcp</string>
		<string>.ra</string>
		<string>.rmi</string>
		<string>.snd</string>
		<string>.s3m</string>
		<string>.spx</string>
		<string>.tta</string>
		<string>.voc</string>
		<string>.vqf</string>
		<string>.w64</string>
		<string>.wav</string>
		<string>.wma</string>
		<string>.wv</string>
		<string>.xa</string>
		<string>.xm</string>
		<string>.3g2</string>
		<string>.3gp</string>
		<string>.3gp2</string>
		<string>.3gpp</string>
		<string>.amv</string>
		<string>.asf</string>
		<string>.avi</string>
		<string>.bik</string>
		<string>.divx</string>
		<string>.drc</string>
		<string>.dv</string>
		<string>.f4v</string>
		<string>.flv</string>
		<string>.gvi</string>
		<string>.gxf</string>
		<string>.m1v</string>
		<string>.m2t</string>
		<string>.m2v</string>
		<string>.m2ts</string>
		<string>.m4v</string>
		<string>.mkv</string>
		<string>.mov</string>
		<string>.mp2v</string>
		<string>.mp4</string>
		<string>.mp4v</string>
		<string>.mpa</string>
		<string>.mpe</string>
		<string>.mpeg</string>
		<string>.mpeg1</string>
		<string>.mpeg2</string>
		<string>.mpeg4</string>
		<string>.mpg</string>
		<string>.mpv2</string>
		<string>.mts</string>
		<string>.mtv</string>
		<string>.mxf</string>
		<string>.nsv</string>
		<string>.nuv</string>
		<string>.ogg</string>
		<string>.ogm</string>
		<string>.ogx</string>
		<string>.ogv</string>
		<string>.rec</string>
		<string>.rm</string>
		<string>.rmvb</string>
		<string>.rpl</string>
		<string>.thp</string>
		<string>.tod</string>
		<string>.ts</string>
		<string>.tts</string>
		<string>.vob</string>
		<string>.vro</string>
		<string>.webm</string>
		<string>.wmv</string>
		<string>.xesc</string>
		<string>.asx</string>
		<string>.b4s</string>
		<string>.cue</string>
		<string>.ifo</string>
		<string>.m3u</string>
		<string>.m3u8</string>
		<string>.pls</string>
		<string>.ram</string>
		<string>.sdp</string>
		<string>.vlc</string>
		<string>.wvx</string>
		<string>.xspf</string>
      </FileAssociations>
    </AppType>
  </AppTypes>
</Configuration>`

**Comment by SiL3NC3** [comment]
Added to v1.1
Also checkbox to remove Suffix. ;)
