### ISSUE TITLE
Add support for more types of portable apps

### ISSUE THREAD

**Issue by paradoxicallist** [SiL3NC3/PortableRegistrator#9]
Great app is this. Thank you.

I'd like to see support for image viewers, media players, pdf readers/editors, office suites, mind mapping, etc. Such as:
• IrfanView
• PotPlayer
• SumatraPDF
• foobar2000
• notepad++
• qBittorrent
• SimpleMind

**Comment by SiL3NC3** [comment]
SumatraPDF added to v1.1
